<?php

defined('BASEPATH') OR exit('No direct script access allowed');

class Bid extends qb_Controller {

    public function _init() {
        parent::_init(); // TODO: Change the autogenerated stub
        $this->load->model('v2/Project_model', 'Project_model');
    }

    // 详情-更多详情
    public function intro($bid = 0) {
        $data['title'] = '更多详情';
        $ret = $this->Project_model->moreBidDetail($bid);
        $data['moreDetail'] = array();
        $ret['bidList_vehicle_info'] = [];

        if (API_HDB_SUCCESS == $ret['status'] && !empty($ret['result'])) {
            $data['moreDetail'] = $ret['result'];

            !array_key_exists('approveDate', $data['moreDetail']) && $data['moreDetail']['approveDate'] = '0';

            $data['bidList'] = [];
            !array_key_exists('omsSource', $data['moreDetail']) && $data['moreDetail']['omsSource'] = 0;

            foreach ($data['moreDetail']['memberDescList'] as $key => $value) {
                if ($data['moreDetail']['omsSource'] !== 'xd_v2') {
                    $data['bidList'][$key]['id'] = $value[0];
                    $data['bidList'][$key]['title'] = $value[1];
                    $data['bidList'][$key]['content'] = $value[2];
                } else {//车贷标信息
                    $data['bid_vehicle_info_list'][$value[1]]['name'] = work_array_key_exists($value['1'], 'vehicle_info');
                    $data['bid_vehicle_info_list'][$value[1]]['value'] = $value[2];
                    $data['bid_vehicle_info_list'][$value[1]]['key'] = $value[1];
                }
            }

            unset($data['moreDetail']['memberDescList']);
            if($data['moreDetail']['omsSource'] === 'xd_v2'){
                $userInfo = [
                    'realName'=>['name'=>'借款人','value'=>$data['moreDetail']['realName'],'key'=>'realName'],
                    'idCard'=>['name'=>'身份证号','value'=>$data['moreDetail']['idCard'],'key'=>'idCard'],
                ];

                $data['bid_vehicle_info_list'] = array_merge($userInfo,$data['bid_vehicle_info_list']);

                $vehicle_info = ['realName','idCard','carBrandNo','carNo','licenseDate','agentEvaluate','runKm','carColour'];
                $data['bidList_vehicle_info'] = [];
                foreach ($vehicle_info as $value){

                  $v = $data['bid_vehicle_info_list'][$value];
                  $value === 'agentEvaluate' && $v['value'] .= '元';
                  $value === 'runKm' && $v['value'] .= '公里';

                  $data['bidList_vehicle_info'][] = $v;
                }
            }

            if($data['moreDetail']['bidType'] == 2 && count($data['moreDetail']['memberDataAuthList']) >= 1){
              foreach ($data['moreDetail']['memberDataAuthList'] as $key=>&$value){
                $value['name'] = work_array_key_exists($value[0],'audit_log');
                $value['createDate'] = $value[1]/1000;
              }
            }

        }

        $this->smarty->view('bid/intro', $data);
    }

    // 详情-预计收益
    public function income() {
        $ret['title'] = '收益计算';
        $this->smarty->view('bid/income', $ret);
    }

    // 日息宝常见问题
    public function question() {
        $ret['title'] = '常见问题';
        $this->smarty->view('bid/question', $ret);
    }

    //项目列表
    public function project() {
        $this->smarty->assign('title', '项目');
        $pageIndex = $this->_get('pageIndex');
        $pageSize = $this->_get('pageSize');

        $ret = $this->Project_model->getBidList($pageIndex, $pageSize);
        $list = array();
        if ($ret['status'] == API_HDB_SUCCESS) {
            $this->smarty->assign('bestBidList', array_slice($ret['result']['bestBidList'], 0, 2));//优选理财
            $beginnerList = $ret['result']['beginnerList'][0];

            $this->smarty->assign('beginnerList', $beginnerList);//新手专区

            unset($ret['result']['bestBidList'], $ret['result']['beginnerList'], $ret['result']['planInfoList']);
            foreach ($ret['result'] as $key => $value) {
                if (is_string($value) || empty($value)) {
                    continue;
                }

                $list[$key]['title'] = work_array_key_exists($key, 'bid');
                $typeConfig = [1 => '新手专区', 2 => '定期日息宝', 3 => '银行宝', 4 => '精选项目'];
                if (in_array($list[$key]['title'], $typeConfig)) {
                    $list[$key]['type_id'] = array_search($list[$key]['title'], $typeConfig);
                    $list[$key]['url'] = '/bid/prolist/' . $list[$key]['type_id'];
                } else {
                    $list[$key]['url'] = $list[$key]['title'] === '活期日息宝' ? '/day/currentdetail' : '###';

                }

                foreach ($value as $k => &$v) {
                    array_key_exists('sellTime', $v) || $v['sellTime'] = 0;
                    $v['income_type'] = $list[$key]['title'] === '活期日息宝'?'七日年化收益':work_array_key_exists('', 'income_type');
                    $list[$key]['title'] === '活期日息宝' && $v['borrowRate'] = sprintfNum($v['sevenDayRate']*365);
                }
                $list[$key]['arrs'] = $value;
            }
        }

        $newList['currentRxbList'] = $list['currentRxbList'];
        $newList['regularList'] = $list['regularList'];
        $newList['eliteSelectedList'] = $list['eliteSelectedList'];
        $list = ($newList + $list);

        $this->smarty->assign('list', $list);
        $this->smarty->view('bid/project');
    }


    //定期日息宝列表
    //项目类型 1：新手标 2：定期 3：银行宝 4：精选项目
    public function prolist($type_id = 1) {
        $pageNo = $this->_post('pageIndex');

        $typeConfig = [1 => '新手标', 2 => '定期日息宝', 3 => '银行宝', 4 => '精选项目'];
        $title = '新手标';
        if (array_key_exists($type_id, $typeConfig)) {
            $title = $typeConfig[$type_id];
        } else {
            $type_id = 1;
        }
        $data['title'] = $title;

        $list = $this->Project_model->getMoreBidList($pageNo, $pageSize = 15, $type_id);
        $data['list'] = '';
        if (API_HDB_SUCCESS == $list['status']) {
            $data['list'] = $list['result']['moreBidList'];
        }

        if (isAjax()) {
            showJsonData($data['list'], $pageSize);
        } else {
            $data['page_url'] = '/bid/prolist/' . $type_id;
            $this->smarty->view('bid/prolist', $data);
        }
    }

    //投标记录
    public function bidlog($bid = '') {
        $data['title'] = '投标记录';
        $pageIndex = $this->_post('pageIndex');
        $bid = empty($this->_get('bid')) ? $bid : $this->_post('bid');
        $data['bid'] = $bid;

        $ret = $this->Project_model->investRecord($pageIndex, $pageSize=15, $bid);
        $data['list'] = array();
        if (API_HDB_SUCCESS == $ret['status'] && !empty($ret['result']['count'])) {
            $data['list'] = $ret['result']['investBidList'];

            $keys = ['bidAmount', 'createDate'];
            update_array_value($data['list'], $keys);
        }

        if (isAjax()) {
            showJsonData($data['list'], $pageSize);
        } else {
            $this->smarty->view('bid/bidlog', $data);
        }
    }

    //标详情
    public function regulardetail($bid = 0) {
        $ret = $this->Project_model->bidDetail($bid);
        $data['result'] = $ret['result'];
        !isset($data['result']['selltime']) && $data['result']['selltime'] = 0;
        $data['isNew'] = _Super_checkMemberIsNew();
        $data['isNewBid'] = work_array_key_exists($data['result']['bidType'], 'bidType') === '新手标' ? 1 : 0;

        $data['result']['SurplusTime'] = $data['result']['bidType'] === 0 ? $data['result']['selltime'] : $data['result']['lastDate'];
        $data['title'] = !empty($data['result']['borrowTitle']) ? $data['result']['borrowTitle'] : '标详情';
        
        $this->smarty->view('bid/regulardetail', $data);
    }

    //项目投标
    public function buy($bid = 0) {
        $data['title'] = '项目投标';
        $ret = $this->Project_model->bidDetail($bid);
        if (API_HDB_SUCCESS == $ret['status']) {
            $sAmount = $ret['result']['sAmount'];
            $data['sAmount'] = $sAmount;
        } else {
            showError();
        }

        //获取可用优惠卷列表
        _Super_queryUserCoupon();

        $ret = $this->My_model->userAccountData();
        if (API_HDB_SUCCESS == $ret['status']) {
            $data['usableAmount'] = $ret['result']['usableAmount'];
        }
        $data['bid'] = $bid;
        $data['couponUrl'] = '/bid/getCouponid';
        $this->smarty->view('bid/buy', $data);
    }


    //获取最优优惠卷
    public function getCouponid() {
        $money = $this->_post('money');
        _Super_queryUserCoupon($money);
    }

    /*
     * 投标操作
     * 1.检测是否登录-------check_Login
     * 2.检测是否实名认证----check_Realname
     * 3.检测是否有快捷卡
     *
     * */
    public function do_buy($bid = 0) {
        $this->_post('money') > $this->_post('usableAmount') && showJsonMsg(API_FAILURE, '账户余额不足');
        $investAmount = $this->_post('money');
        $resourceCode = $this->_post('coupon_code');
        $investAmount % 100 != 0 && showJsonMsg(API_FAILURE, '请输入金额（100的倍数）');
        $ret = $this->Project_model->bidWithCoupon($bid, $investAmount, $resourceCode);

        if (API_HDB_SUCCESS == $ret['status']) {
            if ($investAmount <= 1000) {
                $ratio = '20%-50%';
            } elseif ($investAmount <= 50000) {
                $ratio = '50%-90%';
            } else {
                $ratio = '90%-99%';
            }
            $result['url'] = '/my/subsidiary/bids_records';
            $result['ratio'] = $ratio;
            showJsonResult($result, '恭喜您投标成功!');
        } elseif (4620 == $ret['status']) {//余额不足
            goRedirect(API_FAILURE, '/my/cashvalue/recharge', $ret['message']);
        } else {
            showJsonMsg(API_FAILURE, $ret['message']);
        }
    }

    //投标成功
    public function invest_success() {
        $data['title'] = '投标成功';

        $buy = $this->_getSession('buy', '__TEMP');
        if ($buy['money'] <= 1000) {
            $ratio = '20%-50%';
        } elseif ($buy['money'] <= 50000) {
            $ratio = '50%-90%';
        } else {
            $ratio = '90%-99%';
        }
        $data['ratio'] = $ratio;

        $data['button_top_url'] = '/my/subsidiary/bids_records';
        $this->smarty->view('bid/invest_success', $data);
    }

    //投标失败
    public function invest_error() {
        $data['title'] = '投标失败';
        $this->smarty->view('bid/invest_error', $data);
    }

    //转入
    public function shift_to() {
        $data['title'] = '转入';
        $ret = $this->My_model->userAccountData();
        $data['usableAmount'] = floor($ret['result']['usableAmount']);
        $data['userMoney'] = $ret['result']['usableAmount'];
        $helperRet = _Super_currentRxbDetail();
        if (!empty($helperRet)) {
            $data['icome_time'] = date('m-d', $helperRet['interestDateNext']);
            $data['remainnum'] = NumToStr($helperRet['remainnum']);
        }

        $this->smarty->view('bid/shift_to', $data);
    }

    //转入--操作
    public function do_shift_to() {
        $money = $this->_post('money');
        $ret = $this->Project_model->intoCurrentRxb($money);
        if (API_HDB_SUCCESS == $ret['status']) {
            $result['url'] = '/bid/shift_to';
            $result['money'] = formatMoney($money);
            $result['expiration_time'] = date('m-d', $ret['result']['getInterestDate']);
            showJsonResult($result, '转入成功');
        } elseif (4624 == $ret['status']) {//活期转入失败
            goRedirect(API_ALERT_TWO_BUTTON, '/my/cashvalue/recharge', $ret['message']);
        } else {
            showJsonMsg(API_FAILURE, $ret['message']);
        }
    }

    //转入成功
    public function shift_to_success() {
        $data['title'] = '转入成功';
        $shift_to = $this->_getSession('shift_to');
        $data['money'] = formatMoney($shift_to['money']);
        $data['icome_time'] = date('m-d', $shift_to['icome_time']);
        $data['button_top_url'] = '/bid/shift_to';
        $data['button_bottom_url'] = '/day/currentdetail';
        $this->smarty->view('bid/shift_to_success', $data);
    }

    //转入失败
    public function shift_to_error() {
        $data['title'] = '转入失败';
        $data['button_top_url'] = '/bid/shift_to';
        $data['button_bottom_url'] = '/day/currentdetail';
        $this->smarty->view('bid/shift_to_error', $data);
    }

    //转出
    public function roll_out() {
        $data['title'] = '转出';
        $ret = _Super_queryPerCurrentBalance();
        $data['accountRemin'] = floor($ret['accountRemin']);
        $data['action_url_one'] = '/common/common_verificationTradePwd';
        $data['action_url_two'] = '/bid/do_roll_out';
        $data['forget_deal_url'] = getRedirectStr('/my/password/forget_deal', true);

        $this->smarty->view('bid/roll_out', $data);
    }

    //转出--操作
    public function do_roll_out() {
        $money = trim($this->_post('money'), '');
        $tradePwd = _DecryptPost('tradePwd');

        $ret = $this->Project_model->currentToBalance($money, $tradePwd);
        if (API_HDB_SUCCESS == $ret['status']) {
            $result['url'] = '/bid/roll_out';
            $result['money'] = formatMoney($money);
            showJsonResult($result, '转出成功');
        } else {
            showJsonMsg(API_FAILURE, $ret['message']);
        }


    }

    //转出成功
    public function roll_out_success() {
        $data['title'] = '转出成功';
        $temp = $this->_getSession('roll_out');
        $data['money'] = formatMoney($temp['money']);
        $data['button_top_url'] = '/bid/roll_out';
        $data['button_bottom_url'] = '/day/currentdetail';
        $this->smarty->view('bid/roll_out_success', $data);
    }

    //转出失败
    public function roll_out_error() {
        $data['title'] = '转出失败';
        $this->smarty->view('bid/roll_out_error', $data);
    }

    // 收益计算器
    public function earn($id = '') {
        echo "<meta http-equiv=refresh content='0; url=http://h5.haodaibao.com/#project/" . $id . "/earn '>";
//    $data['title'] = '收益计算器';
//    $this->smarty->view('bid/earn', $data);
    }

    // 借款合同--静态合同
    public function agreement_bid_do($id) {
        $token = $this->_getCookie('hdbtoken');
        echo "<title>请稍后</title><meta http-equiv=refresh content='0; url=" . HDB_PC_URL . "/hdb/memberContractInfo/contract_s?bid=" . $id . "&token=" . $token . "'>";
    }

    // 借款合同--动态合同
    public function agreement_bid_record($id) {
        $token = $this->_getCookie('hdbtoken');
        echo "<title>请稍后</title><meta http-equiv=refresh content='0; url=" . HDB_PC_URL . "/hdb/memberContractInfo/contract?bid=" . $id . "&token=" . $token . "'>";
    }

    // 风险提示书
    public function riskTip() {
        echo "<title>请稍后</title><meta http-equiv=refresh content='0; url=" . HDB_PC_URL . "/f/hdbOnline/hdbNews/riskTip'>";
    }

    // 理财计划说明
    public function staticexplain() {
        $ret['title'] = '日息宝计划';
        $this->load->model('v2/Project_model', 'Project_model');
        $data = $this->Project_model->getPlanTypeList();
        $result = jsondecode($data['result']);
        $ret['result'] = objectToArray($result[0]);

        $this->smarty->view('bid/staticexplain', $ret);
    }

    // 理财计划更多详情（静态）
    public function staticIntro() {
        $ret['title'] = '更多详情';
        $this->smarty->view('bid/staticIntro', $ret);
    }

    // 理财计划
    public function financial_planning($id = 0) {
        $data['planning'] = $this->Project_model->getPlanInfoDetail($id)['result'];
        $data['title'] = '预计收益';
        $this->smarty->view('bid/financial_planning', $data);
    }
}