<?php
/**
 * Created by PhpStorm.
 * User: luosong
 * Date: 2016/10/17
 * Time: 15:40
 */

defined('BASEPATH') OR exit('No direct script access allowed');

class Coupon extends qb_Controller {

  public function _init() {
    parent::_init(); // TODO: Change the autogenerated stub
    $this->load->model('v2/Project_model', 'Project_model');
  }

  // 我的优惠券 已使用 未使用 历史优惠卷
  public function index() {//目前没有接口获取我的优惠卷
    $view['title'] = '我的优惠券';
    $this->smarty->view('my/coupon/my_coupon_index', $view);
  }


  // 选择优惠券
  public function select() {
    $view['title'] = '选择优惠券';
    $this->smarty->view('my/coupon/select', $view);
  }

  /*
   * 获取优惠卷列表
   * */
  public function getCouponList() {
    $status = $this->_get('status');
    _Super_Get_my_Coupon($status);
  }
}