<?php
/**
 * Created by PhpStorm.
 * User: luosong
 * Date: 2016/10/17
 * Time: 14:59
 */

defined('BASEPATH') OR exit('No direct script access allowed');

class Password extends qb_Controller {

  public function _init() {
    parent::_init(); // TODO: Change the autogenerated stub
    $this->load->model('v2/Password_model', 'Password_model');
  }

  //密码管理
  public function manage() {

    $ret = $this->Realname_model->queryRealname();

    if (API_HDB_SUCCESS == $ret['status']) {

      $data = $ret['result'];

      $data['status'] = 1;
      $data['msg'] = '';
      $data['url'] = '';
      if (-1 == $ret['result']['status']) {//实名失败
        $data['status'] = -1;
        $data['msg'] = '您的身份信息正在认证中,如有疑问拨打客服电话:400-620-8800';
        $data['url'] = '/my/info';
      }
      $data['title'] = '密码管理';
      $this->smarty->assign('Realnameinfo', $data);
      $this->smarty->view('my/password/manage', $data);
    }
  }


  /*---------------------交易密码管理---------------------------*/

  //设置交易密码-操作
  public function do_deal_password() {
    $ret = $this->My_model->userAccountData();
    if (API_HDB_SUCCESS == $ret['status']) {
      $mobilePhone = $ret['result']['mobilePhone'];
    }
    $tradePwd = _DecryptPost('password');
    $ret = $this->Password_model->initTradePwd($mobilePhone, $tradePwd, '', 2);
    if (API_HDB_SUCCESS == $ret['status']) {
      goRedirect(API_SUCCESS, '/my/info', $ret['result']['resmsg'], false);
    } else {
      showJsonMsg(API_FAILURE, $ret['message']);
    }
  }

  /*
   * 忘记交易密码|设置交易密码
   * */
  public function forget_deal() {
    $data['title'] = $this->_get('title') === 'setpwd'?'设置交易密码':'忘记交易密码';
    $data['myinfo'] = array();
    $ret = $this->My_model->userAccountData();
    if (API_HDB_SUCCESS == $ret['status']) {
      $data['mobilePhone'] = $ret['result']['mobilePhone'];
    }
    $data['image'] = 'data:image/jpg;base64,' . codeimg()['image'];
    $data['send_code'] = '/common/send_code/forget_deal';
    $data['action_url'] = getRedirectStr('/my/password/do_forget_deal', true);
    getCodeImg();

    $this->smarty->view('my/password/forget_deal', $data);
  }

  /*
   * 忘记交易密码--操作
   * */
  public function do_forget_deal() {
    $mobilePhone = $this->_post('mobilePhone');
    $tradePwd = _DecryptPost('password');
    $passwordRepeat = _DecryptPost('passwordRepeat');
    $randomCode = $this->_post('identifyCode');
    verifyVerifyCode();
    $tradePwd != $passwordRepeat && showJsonMsg(API_FAILURE, '两次密码不一致');
    $ret = $this->Password_model->initTradePwd($mobilePhone, $tradePwd, $randomCode, 1);
    if (API_HDB_SUCCESS == $ret['status']) {
      goRedirect(API_SUCCESS, '' , $ret['result']['resmsg'],'/my/password/manage');//哪儿进哪出否则跳转到制定地址
    } else {
      showJsonMsg(API_FAILURE, $ret['message']);
    }
  }

  //修改交易密码
  public function revised_deal() {
    // _Super_verificationTradePwd(true, false);

    $data['title'] = '修改交易密码';
    $data['action_url'] = getRedirectStr('/my/password/do_revised_deal', true);

    $this->smarty->view('my/password/revised_deal', $data);
  }

  /*
   * 修改交易密码--操作
   * */
  public function do_revised_deal() {
    $tradePwd = _DecryptPost('oldpassword');
    $newTradePwd = _DecryptPost('password');
    $newTradePwdRepeat = _DecryptPost('newTradePwdRepeat');

    $ret = $this->Password_model->modifyTradePwd($tradePwd, $newTradePwd, $newTradePwdRepeat);
    if (API_HDB_SUCCESS == $ret['status']) {
      goRedirect(API_SUCCESS, '/my/password/manage', $ret['result']['resmsg'], false);
    } else {
      showJsonMsg(API_FAILURE, $ret['message']);
    }
  }

  /*---------------------登录密码管理---------------------------*/

  //修改登录密码
  public function revised_login() {
    $data['title'] = '修改登录密码';
    $data['action_url'] = getRedirectStr('/my/password/do_revised_login_pwd', true);

    $this->smarty->view('my/password/revised_login', $data);
  }

  //修改登录密码
  public function do_revised_login_pwd() {
    $loginPwd = _DecryptPost('old_loginpwd');
    $newLoginPwd = _DecryptPost('password');
    $newLoginPwdRepeat = _DecryptPost('new_LoginPwd_Repeat');

    $ret = $this->Password_model->modifyLoginPwd($loginPwd, $newLoginPwd, $newLoginPwdRepeat);
    if (API_HDB_SUCCESS == $ret['status']) {
      showJsonMsg(API_SUCCESS, $ret['result']['resmsg'], '/my/password/manage');
    } else {
      showJsonMsg(API_FAILURE, $ret['message']);
    }
  }
}